import React, { useState } from "react";

function Icengine() {
  return (
    <div style={{ padding: "10px"}}>
      <h2 style={{ paddingTop: "50px" }}>The IC Engine</h2>
      <div className="row" style={{ padding: "10px" }}>
        <div>
          <p>Machines which can convert chemical energy into mechanical energy are known as Internal 
            combustion engines(IC Engine).</p>
          <p>IC Engines are further classified accordingly:</p>
          <p>(a)Strokes</p>
          <p>(b)Methods of ignition</p>
          <p>(c)Fuel used in the engine</p>
          <p>(d)Number of cylinders and arrangement of cylinders.</p>          
        </div>
        <img src="./images/icengine/1.jpg" style={{ width:"100%", paddingBottom: "10px", paddingTop: "10px" }}  alt="" />

      </div>

      <h2 style={{ paddingTop: "30px" }}>Basic Components</h2>
      <div className="row" style={{ padding: "10px" }}>
        <div style={{ width: "50%" }}>
          <p>(a)Cylinder Block</p>
          <p>(b)Cylinder</p>
          <p>(c)Piston</p>
          <p>(d)Combustion Chamber</p>
          <p>(e)Inlet Manifold</p>
          <p>(f)Exhaust Manifold</p>
          <p>(g)Inlet & Exhaust Valve</p>
          <p>(h)Spark Plug</p>
          <p>(i)Connecting Rod</p>
          <p>(j)Crankshaft</p>
          <p>(k)Piston ring</p>
          <p>(l)Gudgeopn Pin</p>
          <p>(m)Camshaft</p>
        </div>
        <div style={{ width: "50%" }}>
          <img
            src="./images/icengine/4.png"
            height="380px"
            style={{ width: "100%" }}
            alt=""
          />
        </div>
      </div>

      <h2 style={{ paddingTop: "30px" }}>Terminology</h2>
      <div className="row" style={{ padding: "10px" }}>
        <div style={{ width: "50%" }}>
          <p>
            (a)TOP DEAD CENTER (TDC): The topmost possible position of Piston.
          </p>
          <p>(b)BOTTOM DEAD CENTER (BDC): The lowest position of piston.</p>
          <p>(c)Bore: Inside diameter of the cylinder </p>
          <p>(d) Stroke: Distance travelled by piston between TDC and BDC.</p>
          <p>
            (e) Swept Volume (Vs): volume swept by the engine piston during one
            stroke.
          </p>
        </div>
        <div style={{ width: "50%" }}>
          <img
            src="./images/icengine/5.jpg"
            height="350px"
            style={{ width: "100%" }}
            alt=""
          />
        </div>
        <div style={{ width: "100%" }}>
          <p>
            (f) Clearance volume (Vc): volume that remains in the cylinder when
            the engine piston is in the top centre position.
          </p>
          <p>(g) Cylinder Volume = Vs + Vc</p>
          <p>
            h) Compression Ratio (r): ratio of cylinder volume to clearance
            volume.
          </p>
        </div>
      </div>

      <h2 style={{ paddingTop: "30px" }}>Four-Stroke Engine</h2>
      <div className="row" style={{ padding: "10px" }}>
        <div style={{ width: "50%" }}>
          <p>
          A four-stroke (also four-cycle) engine is an internal combustion (IC) engine in which the piston completes four separate strokes while turning the crankshaft. A stroke refers 
          to the full travel of the piston along the cylinder, in either direction. 
          </p>
        </div>
        <div style={{ width: "50%" }}>
          <img src="./images/icengine/3.gif"height="400px"style={{ width: "100%" }}alt=""  />
        </div>
        <img  src="./images/icengine/6.jpg"  style={{ width: "100%", paddingBottom: "10px" }}  alt="" />
        <p>The four separate strokes are termed:</p>
        <p><b>1.Intake:</b> Also known as induction or suction. This stroke of the piston begins at top dead center (T.D.C.) and ends at bottom dead center (B.D.C.). In this stroke the intake valve must be in the open position while the piston pulls an air-fuel mixture into the cylinder by producing vacuum pressure into the cylinder through its 
          downward motion. The piston is moving down as air is being sucked in by the downward motion against the piston</p>
        <p><b>2.Compression:</b> This stroke begins at B.D.C, or just at the end of the suction stroke, and ends at T.D.C. In this stroke the piston compresses the air-fuel mixture in preparation 
          for ignition during the power stroke (below). Both the intake and exhaust valves are closed during this stage.</p>
        <p><b>3.Combustion:</b> Also known as power or ignition. This is the start of the second revolution of the four stroke cycle. At this point the crankshaft has completed a full 360 degree revolution. While the piston is at T.D.C. (the end of the compression stroke) the compressed air-fuel mixture is ignited by a spark plug (in a gasoline engine) or by heat generated by high compression (diesel engines), forcefully
            returning the piston to B.D.C. This stroke produces mechanical work from the engine to turn the crankshaft.</p>
        <p><b>4.Exhaust:</b> Also known as outlet. During the exhaust stroke, the piston, once again, returns from B.D.C. to T.D.C. 
          while the exhaust valve is open. This action expels the spent air-fuel mixture through the exhaust valve.</p>
          <p>For Visual Presentation<a href="https://www.youtube.com/watch?v=fTAUq6G9apg&list=PLNz0cQT03s_a8vFtbhF157O-_WAmRMRwB&index=25">
            <u>Click Here</u></a></p>
  </div>

      <h2 style={{ paddingTop: "30px" }}>Two-Stroke Engine</h2>
      <div className="row" style={{ padding: "10px" }}>
        <div style={{ width: "50%" }}>
          <p>
          A two-stroke (or two-cycle) engine is a type of internal combustion
          engine that completes a power cycle with two strokes (up and down
          movements) of the piston during only one crankshaft revolution. This
          is in contrast to a "four-stroke engine", which requires four strokes
          of the piston to complete a power cycle during two crankshaft
          revolutions. In a two-stroke engine, the end of the combustion stroke
          and the beginning of the compression stroke happen simultaneously,
          with the intake and exhaust (or scavenging) functions occurring at the
          same time.
          </p>
        </div>
        <div style={{ width: "50%" }}>
          <img src="./images/icengine/11.gif"height="300px"style={{ width: "100%" }}alt=""  />
        </div>
        <img src="./images/icengine/10.jpg"height="300px"style={{ width: "100%" }}alt=""  />
        <p>Overall, a two-stroke engine contains two processes:</p>
        <p><b>1.Compression stroke:</b> The inlet port opens, the air-fuel mixture enters the chamber and the piston
           moves upwards compressing this mixture. A spark plug ignites the compressed fuel and begins the power stroke.</p>
        <p><b>2.Power stroke:</b> The heated gas exerts high pressure on the piston, the piston moves downward (expansion), waste 
          heat is exhausted.</p> 
        <p>Compared to four stroke engines, two strokes are lighter, more efficient, have the ability to use lower-grade fuel, and more cost-efficient.
          Therefore, the lighter engines results in a higher power-to-weight ratio (more power for less weight). However, they lack the maneuverability 
          possible in four stroke engines and require more lubrication.This makes two stroke engines ideal for ships (need to carry a lot of cargo), 
           motorcycles, and lawn mowers—whereas a four stroke would be ideal for automobiles like cars and trucks.
           </p>
          
          <p>For Visual Presentation<a href="https://www.youtube.com/watch?v=xNLE8G3pC0k"><u>Click Here</u></a></p>
            
      </div>

      <h2 style={{ paddingTop: "30px" }}>Spark Ignition</h2>
      <div className="row" style={{ padding: "10px" }}>
        <img src="./images/icengine/9.jpg" style={{ width: "100%", paddingBottom: "10px" }} alt=""/>
        <p>
        The term spark-ignition engine refers to internal combustion engines, generally petrol engines, where the combustion process of the air-fuel mixture is ignited by a spark from a spark plug. 
        This is in contrast to compression-ignition engines, typically diesel engines, where the heat generated from compression 
        together with the injection of fuel is enough to initiate the combustion process, without needing any external spark.
        </p>
        <p>The working cycle of both spark-ignition and compression-ignition engines may be either two-stroke or four-stroke.A four-stroke spark-ignition engine is an Otto cycle engine. It consists of following 
          four strokes: suction or intake stroke, compression stroke, expansion or power stroke, exhaust stroke. Each stroke consists of 180 degree
           rotation of crankshaft rotation and hence a four-stroke cycle is completed through 720 degree of crank rotation. Thus for one complete
            cycle there is only one power stroke while the crankshaft turns by two OR MORE revolutions</p>
      </div>

      <img
        src="./images/icengine/7.jpg"
        style={{ width: "100%", paddingBottom: "10px" }}
        alt=""
      />
      <img
        src="./images/icengine/8.jpg"
        style={{ width: "100%", paddingBottom: "10px" }}
        alt=""
      />

      <h2 style={{ paddingTop: "30px" }}>Based on Fuel type</h2>
      <div className="row" style={{ padding: "10px" }}>
        <p><b>1.Diesel:</b> Compression Ignition</p>
        <p><b>2.Petrol(Gasoline):</b> Spark Ignition</p>
      </div>

      <h2 style={{ paddingTop: "30px" }}>Important Points</h2>
      <div className="row" style={{ padding: "10px" }}>
       <p>1.dgdgdfgvf </p>
        <p><b>2.Petrol(Gasoline):</b> Spark Ignition</p>
      </div>

      <h2 style={{ paddingTop: "30px" }}>Resources</h2>
      <div className="row" style={{ padding: "10px" }}>
        <p><a href="">cdvdf</a></p>
        <p><a href="">vfdv</a></p>
        <p><a href="">vdd</a></p>
        <p><a href="">vdfvd</a></p>
      </div>
      <p><a href="">vdd</a></p>
        <p><a href="">vdfvd</a></p>
    </div>
  );
}
export default Icengine;
